export const useCustomerDefaults = () => {
    const DEFAULT_DATE_FORMAT = "YYYY-MM-DD"
    const DEFAULT_COORDINATES_FORMAT = "DDM"

    const DEFAULT_FLEET_LIMIT = 50
    const DEFAULT_FLEET_DOCUMENT_TOTAL_SPACE_LIMIT = 1
    const DEFAULT_FLEET_IMAGE_TOTAL_SPACE_LIMIT = 100

    const DEFAULT_XTL_PORT_MIN = 0.1
    const DEFAULT_XTL_PORT_MAX = 5
    const DEFAULT_XTL_PORT_DEFAULT = 0.5

    const DEFAULT_XTL_STARBOARD_MIN = 0.1
    const DEFAULT_XTL_STARBOARD_MAX = 5
    const DEFAULT_XTL_STARBOARD_DEFAULT = 0.5

    const DEFAULT_SAIL_FORMAT = "RHUMB_LINE"
    const DEFAULT_VESSEL_POSITION_TIMESTAMP_THRESHOLD = 24

    const DEFAULT_MAP_UPDATE_FREQUENCY = 60
    const MAP_UPDATE_FREQUENCY_MIN = 40

    const DEFAULT_PLANNING_SPEED = 20.0;
    const DEFAULT_PLANNING_MIN_SPEED = 0.1;
    const DEFAULT_PLANNING_MAX_SPEED = 99.9;


    const DEFAULT_SMARTLOG_PUBLISH_ON_SAVE = false;
    const DEFAULT_HOME_PREFERENCE = "MAP"

    const DEFAULT_CONSUMPTION_LIMIT = 10;

    return {
        DEFAULT_DATE_FORMAT,
        DEFAULT_COORDINATES_FORMAT,
        DEFAULT_FLEET_LIMIT,
        DEFAULT_FLEET_DOCUMENT_TOTAL_SPACE_LIMIT,
        DEFAULT_FLEET_IMAGE_TOTAL_SPACE_LIMIT,
        DEFAULT_XTL_PORT_MIN,
        DEFAULT_XTL_PORT_MAX,
        DEFAULT_XTL_PORT_DEFAULT,
        DEFAULT_XTL_STARBOARD_MIN,
        DEFAULT_XTL_STARBOARD_MAX,
        DEFAULT_XTL_STARBOARD_DEFAULT,
        DEFAULT_SAIL_FORMAT,
        DEFAULT_VESSEL_POSITION_TIMESTAMP_THRESHOLD,
        DEFAULT_MAP_UPDATE_FREQUENCY,
        MAP_UPDATE_FREQUENCY_MIN,
        DEFAULT_PLANNING_SPEED,
        DEFAULT_PLANNING_MIN_SPEED,
        DEFAULT_PLANNING_MAX_SPEED,
        DEFAULT_SMARTLOG_PUBLISH_ON_SAVE,
        DEFAULT_HOME_PREFERENCE,
        DEFAULT_CONSUMPTION_LIMIT
    }
}